version: '3'
services:
  db:
    image: mysql:8.0  # Usar versión estable
    build: ./mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: docmanager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # Opcional para inicializar datos
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    networks:
      - app_network

  flask_app:
    build: ./flask_app
    container_name: flask_app
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: docmanager
    volumes:
      - uploads:/app/uploads  # Persistir archivos subidos
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  db_data:
  uploads:

networks:
  app_network:
    driver: bridge